# An example of ClusterConfig object specifying subnets for a nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mobile-app
  region: cn-northwest-1

vpc:
  id: vpc-056f83f8db816668c
  cidr: "10.201.0.0/16"
  subnets:
    public:
      public-one:
        id: subnet-0998e8598dc0a8579
      public-two:
        id: subnet-0ac31567324699565
    private:
      private-one:
        id: subnet-0b3fef6c1bb8b5306
      private-two:
        id: subnet-0810e50caed049bfb

managedNodeGroups:
  # private node group
  - name: app-nodegroups
    instanceType: m6i.large
    desiredCapacity: 2
    privateNetworking: true
